package day10;

public class Exam1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
//		int a = 4 / 0;  // /by zero
//		System.out.println(a);
//		int[] a = {1,2,3};   //ArrayIndexOutOfBoundsException
//		System.out.println(a[3]);
         try {
        	 //try 안에서 수행할 문장들에서 예외가 발생하지 않는다면 catch문 다음의 문장들은 수행이 되지 않는되 
        	 //하지만 try 문장안의 문장을 수행하는 도중에 예외가 발생하면 예외에 해당되는 catch문이 수행된다.
         }
	}

}
